@url = http://localhost:3333/api

GET {{url}}/autores

###
GET  {{url}}/autores/10

###
GET {{url}}/post/

###
GET {{url}}/post/27

###
GET  {{url}}/post/autores

###
GET  {{url}}/post/autores/1

###
POST {{url}}/autores
Content-Type: application/json

{
    "nombre": "BBB",
    "email":"BBB@antonio.com",
    "imagen":"Laura.jpg"
}

###
POST {{url}}/post
Content-Type: application/json

{
    "titulo": "el arte de programar y no volverte loco",
    "descripcion": "Manual de programacion y como estrellar el ordenador cuando no sabes donde esta el fallo",
    "fecha_creacion": "2024-10-23",
    "categoria": "Informática",
    "autor_id": 13
}

###
PUT {{url}}/autores/300
Content-Type: application/json

{
    "nombre": "Luis Martinez",
    "email": "luismartinez@example.com",
    "imagen": "luis.jpg"
}

###
DELETE {{url}}/autores/34

